import i18n from '../lib/i18n'
import db from '../db'
import { COLOR_SLOTS, getPalette } from '../config/colorPalettes'

async function migrateColorsOnThemeChange(newTheme) {
  const palette = getPalette(newTheme)

  const personas = await db.personas.filter((p) => p.colorSlot > -1).toArray()
  for (const p of personas) {
    const slot = COLOR_SLOTS[p.colorSlot]
    if (slot && palette[slot]) {
      await db.personas.update(p.id, { color: palette[slot] })
    }
  }

  const threads = await db.threads.filter((t) => t.colorSlot > -1).toArray()
  for (const t of threads) {
    const slot = COLOR_SLOTS[t.colorSlot]
    if (slot && palette[slot]) {
      await db.threads.update(t.id, { color: palette[slot] })
    }
  }
}

function applyThemeClass(theme) {
  const html = document.documentElement
  html.className = html.className
    .split(' ')
    .filter((c) => !c.startsWith('theme-'))
    .join(' ')
  if (theme !== 'light') {
    html.classList.add(`theme-${theme}`)
  }
}

export function applySettingEffect(key, value) {
  SETTING_EFFECTS[key]?.(value)
}

export const CATEGORIES = [
  { id: 'appearance', labelKey: 'settings:categories.appearance' },
  { id: 'api', labelKey: 'settings:categories.api' },
  { id: 'prompting', labelKey: 'settings:categories.prompting' },
  { id: 'defaults', labelKey: 'settings:categories.defaults' },
  { id: 'tts', labelKey: 'settings:categories.tts' },
  { id: 'database', labelKey: 'settings:categories.database' },
]

export const GROUPS = [
  { key: 'assistantButtons', labelKey: 'settings:groups.assistantButtons' },
  { key: 'userButtons', labelKey: 'settings:groups.userButtons' },
  { key: 'apiRequestSectionHeaders', labelKey: 'settings:groups.apiRequestSectionHeaders' },
]

export const SETTINGS = [
  {
    key: 'theme',
    category: 'appearance',
    type: 'select',
    default: 'light',
    options: [
      'light',
      'dark',
      'sepia',
      'pastel',
      'high-contrast',
      'high-contrast-dark',
      'terminal',
    ],
    labelKey: 'settings:appearance.theme.label',
    descKey: 'settings:appearance.theme.desc',
    optionLabels: {
      light: 'settings:themeOptions.light',
      dark: 'settings:themeOptions.dark',
      sepia: 'settings:themeOptions.sepia',
      pastel: 'settings:themeOptions.pastel',
      'high-contrast': 'settings:themeOptions.highContrast',
      'high-contrast-dark': 'settings:themeOptions.highContrastDark',
      terminal: 'settings:themeOptions.terminal',
    },
  },
  {
    key: 'cardsPerPage',
    category: 'appearance',
    type: 'select',
    default: 10,
    options: [5, 10, 25, 50, Infinity],
    labelKey: 'settings:appearance.cardsPerPage.label',
    descKey: 'settings:appearance.cardsPerPage.desc',
    optionLabels: {
      Infinity: 'settings:appearance.cardsPerPageOptions.infinity',
    },
  },
  {
    key: 'language',
    category: 'appearance',
    type: 'select',
    default: 'en',
    options: ['en', 'pt-BR', 'fr', 'it', 'de', 'es'],
    labelKey: 'settings:appearance.language.label',
    descKey: 'settings:appearance.language.desc',
    optionLabels: {
      en: 'settings:languageOptions.en',
      'pt-BR': 'settings:languageOptions.pt-BR',
      fr: 'settings:languageOptions.fr',
      it: 'settings:languageOptions.it',
      de: 'settings:languageOptions.de',
      es: 'settings:languageOptions.es',
    },
  },
  {
    key: 'toastPosition',
    category: 'appearance',
    type: 'select',
    default: 'top-right',
    options: [
      'top-right',
      'top-left',
      'top-center',
      'bottom-right',
      'bottom-left',
      'bottom-center',
    ],
    labelKey: 'settings:appearance.toastPosition.label',
    descKey: 'settings:appearance.toastPosition.desc',
    optionLabels: {
      'top-right': 'settings:toastPositionOptions.top-right',
      'top-left': 'settings:toastPositionOptions.top-left',
      'top-center': 'settings:toastPositionOptions.top-center',
      'bottom-right': 'settings:toastPositionOptions.bottom-right',
      'bottom-left': 'settings:toastPositionOptions.bottom-left',
      'bottom-center': 'settings:toastPositionOptions.bottom-center',
    },
  },
  {
    key: 'toastDuration',
    category: 'appearance',
    type: 'slider',
    default: 4,
    props: { min: 2, max: 15, step: 1 },
    labelKey: 'settings:appearance.toastDuration.label',
    descKey: 'settings:appearance.toastDuration.desc',
  },
  {
    key: 'sidebarTogglePosition',
    category: 'appearance',
    type: 'select',
    default: 'bottom-left',
    options: [
      'bottom-left',
      'bottom-right',
      'bottom-center',
      'top-left',
      'top-right',
      'top-center',
    ],
    labelKey: 'settings:appearance.sidebarTogglePosition.label',
    descKey: 'settings:appearance.sidebarTogglePosition.desc',
    optionLabels: {
      'bottom-left': 'settings:sidebarTogglePositionOptions.bottom-left',
      'bottom-right': 'settings:sidebarTogglePositionOptions.bottom-right',
      'bottom-center': 'settings:sidebarTogglePositionOptions.bottom-center',
      'top-left': 'settings:sidebarTogglePositionOptions.top-left',
      'top-right': 'settings:sidebarTogglePositionOptions.top-right',
      'top-center': 'settings:sidebarTogglePositionOptions.top-center',
    },
  },
  {
    key: 'sidebarNavLayout',
    category: 'appearance',
    type: 'select',
    default: 'vertical',
    options: ['vertical', 'compact'],
    labelKey: 'settings:appearance.sidebarNavLayout.label',
    descKey: 'settings:appearance.sidebarNavLayout.desc',
    optionLabels: {
      vertical: 'settings:sidebarNavLayoutOptions.vertical',
      compact: 'settings:sidebarNavLayoutOptions.compact',
    },
  },
  {
    key: 'showAssistantDelete',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantDelete.label',
    descKey: 'settings:appearance.showAssistantDelete.desc',
  },
  {
    key: 'showAssistantEdit',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantEdit.label',
    descKey: 'settings:appearance.showAssistantEdit.desc',
  },
  {
    key: 'showAssistantCopy',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantCopy.label',
    descKey: 'settings:appearance.showAssistantCopy.desc',
  },
  {
    key: 'showAssistantFork',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantFork.label',
    descKey: 'settings:appearance.showAssistantFork.desc',
  },
  {
    key: 'showAssistantRegenerate',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantRegenerate.label',
    descKey: 'settings:appearance.showAssistantRegenerate.desc',
  },
  {
    key: 'showAssistantSpeak',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantSpeak.label',
    descKey: 'settings:appearance.showAssistantSpeak.desc',
  },
  {
    key: 'showAssistantPrompt',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantPrompt.label',
    descKey: 'settings:appearance.showAssistantPrompt.desc',
  },
  {
    key: 'assistantButtonOrder',
    category: 'appearance',
    type: 'buttonOrder',
    default: ['delete', 'edit', 'copy', 'fork', 'regenerate', 'speak', 'prompt'],
    group: 'assistantButtons',
    labelKey: 'settings:appearance.assistantButtonOrder.label',
    descKey: 'settings:appearance.assistantButtonOrder.desc',
    props: {
      buttons: [
        { key: 'delete', labelKey: 'settings:appearance.showAssistantDelete.label' },
        { key: 'edit', labelKey: 'settings:appearance.showAssistantEdit.label' },
        { key: 'copy', labelKey: 'settings:appearance.showAssistantCopy.label' },
        { key: 'fork', labelKey: 'settings:appearance.showAssistantFork.label' },
        { key: 'regenerate', labelKey: 'settings:appearance.showAssistantRegenerate.label' },
        { key: 'speak', labelKey: 'settings:appearance.showAssistantSpeak.label' },
        { key: 'prompt', labelKey: 'settings:appearance.showAssistantPrompt.label' },
      ],
    },
  },
  {
    key: 'showUserDelete',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserDelete.label',
    descKey: 'settings:appearance.showUserDelete.desc',
  },
  {
    key: 'showUserEdit',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserEdit.label',
    descKey: 'settings:appearance.showUserEdit.desc',
  },
  {
    key: 'showUserCopy',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserCopy.label',
    descKey: 'settings:appearance.showUserCopy.desc',
  },
  {
    key: 'showUserFork',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserFork.label',
    descKey: 'settings:appearance.showUserFork.desc',
  },
  {
    key: 'userButtonOrder',
    category: 'appearance',
    type: 'buttonOrder',
    default: ['delete', 'edit', 'copy', 'fork'],
    group: 'userButtons',
    labelKey: 'settings:appearance.userButtonOrder.label',
    descKey: 'settings:appearance.userButtonOrder.desc',
    props: {
      buttons: [
        { key: 'delete', labelKey: 'settings:appearance.showUserDelete.label' },
        { key: 'edit', labelKey: 'settings:appearance.showUserEdit.label' },
        { key: 'copy', labelKey: 'settings:appearance.showUserCopy.label' },
        { key: 'fork', labelKey: 'settings:appearance.showUserFork.label' },
      ],
    },
  },
  {
    key: 'characterCardMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.characterCardMarquee.label',
    descKey: 'settings:appearance.characterCardMarquee.desc',
  },
  {
    key: 'threadCardMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.threadCardMarquee.label',
    descKey: 'settings:appearance.threadCardMarquee.desc',
  },
  {
    key: 'chatTitleMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.chatTitleMarquee.label',
    descKey: 'settings:appearance.chatTitleMarquee.desc',
  },
  {
    key: 'unreadBadges',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.unreadBadges.label',
    descKey: 'settings:appearance.unreadBadges.desc',
  },
  {
    key: 'highlightDeleteButtons',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.highlightDeleteButtons.label',
    descKey: 'settings:appearance.highlightDeleteButtons.desc',
  },
  {
    key: 'regenerationConfirmation',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.regenerationConfirmation.label',
    descKey: 'settings:appearance.regenerationConfirmation.desc',
  },
  {
    key: 'unreadSound',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.unreadSound.label',
    descKey: 'settings:appearance.unreadSound.desc',
  },
  {
    key: 'chatFontFamily',
    category: 'appearance',
    type: 'select',
    default: 'system',
    options: ['system', 'inter', 'atkinson', 'roboto', 'georgia', 'courier', 'trebuchet'],
    labelKey: 'settings:appearance.chatFontFamily.label',
    descKey: 'settings:appearance.chatFontFamily.desc',
    optionLabels: {
      system: 'settings:appearance.chatFontFamilyOptions.system',
      inter: 'settings:appearance.chatFontFamilyOptions.inter',
      atkinson: 'settings:appearance.chatFontFamilyOptions.atkinson',
      roboto: 'settings:appearance.chatFontFamilyOptions.roboto',
      georgia: 'settings:appearance.chatFontFamilyOptions.georgia',
      courier: 'settings:appearance.chatFontFamilyOptions.courier',
      trebuchet: 'settings:appearance.chatFontFamilyOptions.trebuchet',
    },
  },
  {
    key: 'chatFontSize',
    category: 'appearance',
    type: 'select',
    default: 'sm',
    options: ['xs', 'sm', 'base', 'lg', 'xl'],
    labelKey: 'settings:appearance.chatFontSize.label',
    descKey: 'settings:appearance.chatFontSize.desc',
    optionLabels: {
      xs: 'settings:appearance.chatFontSizeOptions.xs',
      sm: 'settings:appearance.chatFontSizeOptions.sm',
      base: 'settings:appearance.chatFontSizeOptions.base',
      lg: 'settings:appearance.chatFontSizeOptions.lg',
      xl: 'settings:appearance.chatFontSizeOptions.xl',
    },
  },
  {
    key: 'defaultAutoTitle',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.autoTitle.label',
    descKey: 'settings:defaults.autoTitle.desc',
  },
  {
    key: 'defaultAutoTitleThreshold',
    category: 'defaults',
    type: 'text',
    default: 3,
    props: { type: 'number' },
    labelKey: 'settings:defaults.autoTitleThreshold.label',
    descKey: 'settings:defaults.autoTitleThreshold.desc',
  },
  {
    key: 'defaultMemory',
    category: 'defaults',
    type: 'select',
    default: 'messages',
    options: ['never', 'messages', 'contextWindow'],
    labelKey: 'settings:defaults.memory.label',
    descKey: 'settings:defaults.memory.desc',
    optionLabels: {
      never: 'settings:defaults.memoryOptions.never',
      messages: 'settings:defaults.memoryOptions.messages',
      contextWindow: 'settings:defaults.memoryOptions.contextWindow',
    },
  },
  {
    key: 'defaultMessagesThreshold',
    category: 'defaults',
    type: 'text',
    default: 7,
    props: { type: 'number' },
    labelKey: 'settings:defaults.messagesThreshold.label',
    descKey: 'settings:defaults.messagesThreshold.desc',
    dependsOn: { key: 'defaultMemory', value: 'messages' },
  },
  {
    key: 'defaultContextWindowThreshold',
    category: 'defaults',
    type: 'slider',
    default: 1024,
    props: { min: 256, max: 8192, step: 256 },
    labelKey: 'settings:defaults.contextWindowThreshold.label',
    descKey: 'settings:defaults.contextWindowThreshold.desc',
    dependsOn: { key: 'defaultMemory', value: 'contextWindow' },
  },
  {
    key: 'defaultMessagesToKeep',
    category: 'defaults',
    type: 'text',
    default: 5,
    props: { type: 'number', min: 0, max: 50, step: 1 },
    labelKey: 'settings:defaults.messagesToKeep.label',
    descKey: 'settings:defaults.messagesToKeep.desc',
    dependsOn: { key: 'defaultMemory', value: 'never', not: true },
  },
  {
    key: 'defaultMemorySlots',
    category: 'defaults',
    type: 'text',
    default: 3,
    props: { type: 'number', min: 1, max: 5, step: 1 },
    labelKey: 'settings:defaults.memorySlots.label',
    descKey: 'settings:defaults.memorySlots.desc',
    dependsOn: { key: 'defaultMemory', value: 'never', not: true },
  },
  {
    key: 'defaultFirstMessage',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.firstMessage.label',
    descKey: 'settings:defaults.firstMessage.desc',
  },
  {
    key: 'defaultUserPersonaPrefix',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.userPersonaPrefix.label',
    descKey: 'settings:defaults.userPersonaPrefix.desc',
  },
  {
    key: 'defaultIncludeOOC',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.includeOOC.label',
    descKey: 'settings:defaults.includeOOC.desc',
  },
  {
    key: 'defaultMessageThreshold',
    category: 'defaults',
    type: 'text',
    default: 0,
    props: { type: 'number', min: 0 },
    labelKey: 'settings:defaults.messageThreshold.label',
    descKey: 'settings:defaults.messageThreshold.desc',
  },
  {
    key: 'defaultPostProcessing',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.postProcessing.label',
    descKey: 'settings:defaults.postProcessing.desc',
  },
  {
    key: 'defaultSystemAvatar',
    category: 'defaults',
    type: 'avatar',
    default: '',
    labelKey: 'settings:defaults.systemAvatar.label',
    descKey: 'settings:defaults.systemAvatar.desc',
  },
  {
    key: 'defaultSystemAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.systemAvatarScale.label',
    descKey: 'settings:defaults.systemAvatarScale.desc',
  },
  {
    key: 'defaultCharacterAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.characterAvatarScale.label',
    descKey: 'settings:defaults.characterAvatarScale.desc',
  },
  {
    key: 'defaultUserPersonaAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.userPersonaAvatarScale.label',
    descKey: 'settings:defaults.userPersonaAvatarScale.desc',
  },
  {
    key: 'requestKind.chat.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.chatProfile.label',
    descKey: 'settings:api.chatProfile.desc',
  },
  {
    key: 'requestKind.autoTitle.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.autoTitleProfile.label',
    descKey: 'settings:api.autoTitleProfile.desc',
  },
  {
    key: 'requestKind.summarization.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.summarizationProfile.label',
    descKey: 'settings:api.summarizationProfile.desc',
  },
  {
    key: 'requestKind.ooc.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.oocProfile.label',
    descKey: 'settings:api.oocProfile.desc',
  },
  {
    key: 'requestKind.director.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.directorProfile.label',
    descKey: 'settings:api.directorProfile.desc',
  },
  {
    key: 'api.requestCooldown',
    category: 'api',
    type: 'slider',
    default: 2,
    props: { min: 2, max: 10, step: 0.5 },
    labelKey: 'settings:api.requestCooldown.label',
    descKey: 'settings:api.requestCooldown.desc',
  },
  {
    key: 'prompting.autoTitleSystem',
    category: 'prompting',
    type: 'textarea',
    default: 'You are a title generator for conversational AI.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.autoTitleSystem.label',
    descKey: 'settings:prompting.autoTitleSystem.desc',
  },
  {
    key: 'prompting.autoTitleUser',
    category: 'prompting',
    type: 'textarea',
    default:
      'Read the following thread and create one concise title (7 words max, in Title Case) capturing its core topic in plain-text (output the title ONLY, no markup, no formatting):\n\n{{transcript}}',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.autoTitleUser.label',
    descKey: 'settings:prompting.autoTitleUser.desc',
  },
  {
    key: 'prompting.summarizationSystem',
    category: 'prompting',
    type: 'textarea',
    default:
      "You are a memory generator for conversational AI.\n\nGenerate a plain-text summary strictly based on the provided content minding these rules:\n\n- Read all `# MESSAGES`, and extract key facts from them\n- Don't re-summarize any `# MEMORY` entry already present, eliminate duplicates\n- Write the key facts in a concise, short, pragmatic, matter-of-fact style, in 2 paragraphs max, under 192 tokens total\n- Never write any quoted dialogue, inner monologue, or speculation\n- Never invent, continue, or give closure to scenes\n- Write in plain-text only",
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.summarizationSystem.label',
    descKey: 'settings:prompting.summarizationSystem.desc',
  },
  {
    key: 'prompting.summarizationUser',
    category: 'prompting',
    type: 'textarea',
    default: 'Summarize this:',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.summarizationUser.label',
    descKey: 'settings:prompting.summarizationUser.desc',
  },
  {
    key: 'prompting.oocDelimiters',
    category: 'prompting',
    type: 'oocDelimiters',
    default: { enabled: false, left: '((OOC: ', right: '))' },
    labelKey: 'settings:prompting.oocDelimiters.label',
    descKey: 'settings:prompting.oocDelimiters.desc',
  },
  {
    key: 'prompting.oocSystem',
    category: 'prompting',
    type: 'textarea',
    default: 'This is an OOC request. Reply in OOC. Be concise, pragmatic, and exact.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.oocSystem.label',
    descKey: 'settings:prompting.oocSystem.desc',
  },
  {
    key: 'prompting.oocMessageRole',
    category: 'prompting',
    type: 'select',
    default: 'system',
    options: ['system', 'assistant'],
    labelKey: 'settings:prompting.oocMessageRole.label',
    descKey: 'settings:prompting.oocMessageRole.desc',
    optionLabels: {
      system: 'settings:prompting.oocMessageRoleOptions.system',
      assistant: 'settings:prompting.oocMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.oocUser',
    category: 'prompting',
    type: 'textarea',
    default: '((OOC: {content}))',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.oocUser.label',
    descKey: 'settings:prompting.oocUser.desc',
  },
  {
    key: 'prompting.personaInjectionTemplate',
    category: 'prompting',
    type: 'textarea',
    default: '\n\n---\n\n**User**:\n\n- Name: {{name}}\n- {{description}}',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.personaInjectionTemplate.label',
    descKey: 'settings:prompting.personaInjectionTemplate.desc',
  },
  {
    key: 'prompting.systemRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '[SYSTEM]:',
    labelKey: 'settings:prompting.systemRolePrefix.label',
    descKey: 'settings:prompting.systemRolePrefix.desc',
  },
  {
    key: 'prompting.assistantRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '[ASSISTANT]:',
    labelKey: 'settings:prompting.assistantRolePrefix.label',
    descKey: 'settings:prompting.assistantRolePrefix.desc',
  },
  {
    key: 'prompting.userRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '[USER]:',
    labelKey: 'settings:prompting.userRolePrefix.label',
    descKey: 'settings:prompting.userRolePrefix.desc',
  },
  {
    key: 'prompting.userRolePrefixWithPersona',
    category: 'prompting',
    type: 'text',
    default: '[USER as {{persona_name}}]:',
    labelKey: 'settings:prompting.userRolePrefixWithPersona.label',
    descKey: 'settings:prompting.userRolePrefixWithPersona.desc',
  },
  {
    key: 'prompting.systemRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '[SYSTEM in OOC]:',
    labelKey: 'settings:prompting.systemRolePrefixOoc.label',
    descKey: 'settings:prompting.systemRolePrefixOoc.desc',
  },
  {
    key: 'prompting.assistantRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '[ASSISTANT in OOC]:',
    labelKey: 'settings:prompting.assistantRolePrefixOoc.label',
    descKey: 'settings:prompting.assistantRolePrefixOoc.desc',
  },
  {
    key: 'prompting.userRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '[USER in OOC]:',
    labelKey: 'settings:prompting.userRolePrefixOoc.label',
    descKey: 'settings:prompting.userRolePrefixOoc.desc',
  },
  {
    key: 'prompting.writingInjectionTiming',
    category: 'defaults',
    type: 'select',
    default: 'always',
    options: ['always', 'never'],
    labelKey: 'settings:defaults.writingInjectionTiming.label',
    descKey: 'settings:defaults.writingInjectionTiming.desc',
    optionLabels: {
      always: 'settings:defaults.writingInjectionTimingOptions.always',
      never: 'settings:defaults.writingInjectionTimingOptions.never',
    },
  },
  {
    key: 'prompting.writingPlacement',
    category: 'defaults',
    type: 'select',
    default: 'endOfSystemPrompt',
    options: ['endOfSystemPrompt', 'endOfMessages'],
    dependsOn: { key: 'prompting.writingInjectionTiming', value: 'always' },
    labelKey: 'settings:defaults.writingPlacement.label',
    descKey: 'settings:defaults.writingPlacement.desc',
    optionLabels: {
      endOfSystemPrompt: 'settings:defaults.writingPlacementOptions.endOfSystemPrompt',
      endOfMessages: 'settings:defaults.writingPlacementOptions.endOfMessages',
    },
  },
  {
    key: 'prompting.writingMessageRole',
    category: 'defaults',
    type: 'select',
    default: 'system',
    options: ['system', 'assistant'],
    dependsOn: [
      { key: 'prompting.writingPlacement', value: 'endOfMessages' },
      { key: 'prompting.writingInjectionTiming', value: 'always' },
    ],
    labelKey: 'settings:defaults.writingMessageRole.label',
    descKey: 'settings:defaults.writingMessageRole.desc',
    optionLabels: {
      system: 'settings:defaults.writingMessageRoleOptions.system',
      assistant: 'settings:defaults.writingMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.personaInjectionTiming',
    category: 'defaults',
    type: 'select',
    default: 'always',
    options: ['always', 'never'],
    labelKey: 'settings:defaults.personaInjectionTiming.label',
    descKey: 'settings:defaults.personaInjectionTiming.desc',
    optionLabels: {
      always: 'settings:defaults.personaInjectionTimingOptions.always',
      never: 'settings:defaults.personaInjectionTimingOptions.never',
    },
  },
  {
    key: 'personaInjectionPlacement',
    category: 'defaults',
    type: 'select',
    default: 'endOfSystemPrompt',
    options: ['endOfSystemPrompt', 'endOfMessages'],
    dependsOn: { key: 'prompting.personaInjectionTiming', value: 'always' },
    labelKey: 'settings:defaults.personaInjectionPlacement.label',
    descKey: 'settings:defaults.personaInjectionPlacement.desc',
    optionLabels: {
      endOfSystemPrompt: 'settings:defaults.personaInjectionPlacementOptions.endOfSystemPrompt',
      endOfMessages: 'settings:defaults.personaInjectionPlacementOptions.endOfMessages',
    },
  },
  {
    key: 'personaInjectionMessageRole',
    category: 'defaults',
    type: 'select',
    default: 'system',
    options: ['system', 'assistant'],
    dependsOn: [
      { key: 'personaInjectionPlacement', value: 'endOfMessages' },
      { key: 'prompting.personaInjectionTiming', value: 'always' },
    ],
    labelKey: 'settings:defaults.personaInjectionMessageRole.label',
    descKey: 'settings:defaults.personaInjectionMessageRole.desc',
    optionLabels: {
      system: 'settings:defaults.personaInjectionMessageRoleOptions.system',
      assistant: 'settings:defaults.personaInjectionMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.firstMessageRole',
    category: 'prompting',
    type: 'select',
    default: 'user',
    options: ['system', 'assistant', 'user'],
    labelKey: 'settings:prompting.firstMessageRole.label',
    descKey: 'settings:prompting.firstMessageRole.desc',
    optionLabels: {
      system: 'settings:prompting.firstMessageRoleOptions.system',
      assistant: 'settings:prompting.firstMessageRoleOptions.assistant',
      user: 'settings:prompting.firstMessageRoleOptions.user',
    },
  },
  {
    key: 'prompting.firstMessagePrompt',
    category: 'prompting',
    type: 'textarea',
    default: '((OOC: Start with the first message, always sticking to the AI writing rules))',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.firstMessagePrompt.label',
    descKey: 'settings:prompting.firstMessagePrompt.desc',
  },
  {
    key: 'prompting.continueRole',
    category: 'prompting',
    type: 'select',
    default: 'user',
    options: ['system', 'assistant', 'user'],
    labelKey: 'settings:prompting.continueRole.label',
    descKey: 'settings:prompting.continueRole.desc',
    optionLabels: {
      system: 'settings:prompting.continueRoleOptions.system',
      assistant: 'settings:prompting.continueRoleOptions.assistant',
      user: 'settings:prompting.continueRoleOptions.user',
    },
  },
  {
    key: 'prompting.continuePrompt',
    category: 'prompting',
    type: 'textarea',
    default: '((OOC: Continue the current scene, always sticking to the AI writing rules))',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.continuePrompt.label',
    descKey: 'settings:prompting.continuePrompt.desc',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.characterPrompt',
    category: 'prompting',
    type: 'text',
    default: 'Description:',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.characterPrompt.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.messages',
    category: 'prompting',
    type: 'text',
    default: 'Messages:',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.messages.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.memories',
    category: 'prompting',
    type: 'text',
    default: 'Memories:',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.memories.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.memoryEntry',
    category: 'prompting',
    type: 'text',
    default: 'Memory Level {{level}} Entry {{slot}}:',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.memoryEntry.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.loreContext',
    category: 'prompting',
    type: 'text',
    default: 'Lore:',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.loreContext.label',
  },
]

const SETTING_EFFECTS = {
  theme: (value) => {
    applyThemeClass(value)
    migrateColorsOnThemeChange(value)
  },
  language: (value) => i18n.changeLanguage(value),
  highlightDeleteButtons: (value) => {
    document.documentElement.classList.toggle('show-delete-highlight', !!value)
  },
}

export async function getSetting(key) {
  const rows = await db.settings.where('key').equals(key).toArray()
  const def = SETTINGS.find((s) => s.key === key)?.default
  if (rows.length > 1) {
    const keep = rows[rows.length - 1]
    await db.settings.bulkDelete(rows.filter((r) => r.id !== keep.id).map((r) => r.id))
    return keep.value ?? def ?? null
  }
  return rows[0]?.value ?? def ?? null
}

export async function setSetting(key, value) {
  const existing = await db.settings.where('key').equals(key).first()
  if (existing) {
    await db.settings.update(existing.id, { value })
  } else {
    await db.settings.add({ key, value })
  }
  SETTING_EFFECTS[key]?.(value)
  window.dispatchEvent(new CustomEvent('settings-changed', { detail: { key, value } }))
}
