import i18n from '../lib/i18n'
import db from '../db'
import { COLOR_SLOTS, getPalette } from '../config/colorPalettes'

async function migrateColorsOnThemeChange(newTheme) {
  const palette = getPalette(newTheme)

  const personas = await db.personas.filter((p) => p.colorSlot > -1).toArray()
  for (const p of personas) {
    const slot = COLOR_SLOTS[p.colorSlot]
    if (slot && palette[slot]) {
      await db.personas.update(p.id, { color: palette[slot] })
    }
  }

  const threads = await db.threads.filter((t) => t.colorSlot > -1).toArray()
  for (const t of threads) {
    const slot = COLOR_SLOTS[t.colorSlot]
    if (slot && palette[slot]) {
      await db.threads.update(t.id, { color: palette[slot] })
    }
  }
}

function applyThemeClass(theme) {
  const html = document.documentElement
  html.className = html.className
    .split(' ')
    .filter((c) => !c.startsWith('theme-'))
    .join(' ')
  if (theme !== 'light') {
    html.classList.add(`theme-${theme}`)
  }
}

export function applySettingEffect(key, value) {
  SETTING_EFFECTS[key]?.(value)
}

export const CATEGORIES = [
  { id: 'appearance', labelKey: 'settings:categories.appearance' },
  { id: 'api', labelKey: 'settings:categories.api' },
  { id: 'prompting', labelKey: 'settings:categories.prompting' },
  { id: 'defaults', labelKey: 'settings:categories.defaults' },
  { id: 'tts', labelKey: 'settings:categories.tts' },
  { id: 'database', labelKey: 'settings:categories.database' },
]

export const GROUPS = [
  { key: 'assistantButtons', labelKey: 'settings:groups.assistantButtons' },
  { key: 'userButtons', labelKey: 'settings:groups.userButtons' },
  { key: 'apiRequestSectionHeaders', labelKey: 'settings:groups.apiRequestSectionHeaders' },
  { key: 'chatButtons', labelKey: 'settings:groups.chatButtons' },
  { key: 'rolePrefixes', labelKey: 'settings:groups.rolePrefixes' },
  { key: 'localInference', labelKey: 'settings:groups.localInference' },
  {
    key: 'localInferenceAdvanced',
    labelKey: 'settings:groups.localInferenceAdvanced',
    defaultExpanded: false,
  },
]

export const SETTINGS = [
  {
    key: 'theme',
    category: 'appearance',
    type: 'select',
    default: 'light',
    options: [
      'light',
      'dark',
      'sepia',
      'pastel',
      'high-contrast',
      'high-contrast-dark',
      'terminal',
      'midnight',
      'obsidian',
      'cyberpunk',
      'vaporwave',
      'retro-crt',
      'solarized-dark',
      'neon-abyss',
    ],
    labelKey: 'settings:appearance.theme.label',
    descKey: 'settings:appearance.theme.desc',
    optionLabels: {
      light: 'settings:themeOptions.light',
      dark: 'settings:themeOptions.dark',
      sepia: 'settings:themeOptions.sepia',
      pastel: 'settings:themeOptions.pastel',
      'high-contrast': 'settings:themeOptions.highContrast',
      'high-contrast-dark': 'settings:themeOptions.highContrastDark',
      terminal: 'settings:themeOptions.terminal',
      midnight: 'settings:themeOptions.midnight',
      obsidian: 'settings:themeOptions.obsidian',
      cyberpunk: 'settings:themeOptions.cyberpunk',
      vaporwave: 'settings:themeOptions.vaporwave',
      'retro-crt': 'settings:themeOptions.retroCrt',
      'solarized-dark': 'settings:themeOptions.solarizedDark',
      'neon-abyss': 'settings:themeOptions.neonAbyss',
    },
  },
  {
    key: 'cardsPerPage',
    category: 'appearance',
    type: 'select',
    default: 10,
    options: [5, 10, 25, 50, Infinity],
    labelKey: 'settings:appearance.cardsPerPage.label',
    descKey: 'settings:appearance.cardsPerPage.desc',
    optionLabels: {
      Infinity: 'settings:appearance.cardsPerPageOptions.infinity',
    },
  },
  {
    key: 'discoveryCardSize',
    category: 'appearance',
    type: 'select',
    default: 'regular',
    options: ['smaller', 'small', 'regular', 'large', 'xlarge'],
    labelKey: 'settings:appearance.discoveryCardSize.label',
    descKey: 'settings:appearance.discoveryCardSize.desc',
    optionLabels: {
      smaller: 'settings:appearance.discoveryCardSizeOptions.smaller',
      small: 'settings:appearance.discoveryCardSizeOptions.small',
      regular: 'settings:appearance.discoveryCardSizeOptions.regular',
      large: 'settings:appearance.discoveryCardSizeOptions.large',
      xlarge: 'settings:appearance.discoveryCardSizeOptions.xlarge',
    },
  },
  {
    key: 'language',
    category: 'appearance',
    type: 'select',
    default: 'en',
    options: ['en', 'pt-BR', 'fr', 'it', 'de', 'es'],
    labelKey: 'settings:appearance.language.label',
    descKey: 'settings:appearance.language.desc',
    optionLabels: {
      en: 'settings:languageOptions.en',
      'pt-BR': 'settings:languageOptions.pt-BR',
      fr: 'settings:languageOptions.fr',
      it: 'settings:languageOptions.it',
      de: 'settings:languageOptions.de',
      es: 'settings:languageOptions.es',
    },
  },
  {
    key: 'toastPosition',
    category: 'appearance',
    type: 'select',
    default: 'top-right',
    options: [
      'top-right',
      'top-left',
      'top-center',
      'bottom-right',
      'bottom-left',
      'bottom-center',
    ],
    labelKey: 'settings:appearance.toastPosition.label',
    descKey: 'settings:appearance.toastPosition.desc',
    optionLabels: {
      'top-right': 'settings:toastPositionOptions.top-right',
      'top-left': 'settings:toastPositionOptions.top-left',
      'top-center': 'settings:toastPositionOptions.top-center',
      'bottom-right': 'settings:toastPositionOptions.bottom-right',
      'bottom-left': 'settings:toastPositionOptions.bottom-left',
      'bottom-center': 'settings:toastPositionOptions.bottom-center',
    },
  },
  {
    key: 'toastDuration',
    category: 'appearance',
    type: 'slider',
    default: 4,
    props: { min: 2, max: 15, step: 1 },
    labelKey: 'settings:appearance.toastDuration.label',
    descKey: 'settings:appearance.toastDuration.desc',
  },
  {
    key: 'sidebarTogglePosition',
    category: 'appearance',
    type: 'select',
    default: 'bottom-left',
    options: [
      'bottom-left',
      'bottom-right',
      'bottom-center',
      'top-left',
      'top-right',
      'top-center',
    ],
    labelKey: 'settings:appearance.sidebarTogglePosition.label',
    descKey: 'settings:appearance.sidebarTogglePosition.desc',
    optionLabels: {
      'bottom-left': 'settings:sidebarTogglePositionOptions.bottom-left',
      'bottom-right': 'settings:sidebarTogglePositionOptions.bottom-right',
      'bottom-center': 'settings:sidebarTogglePositionOptions.bottom-center',
      'top-left': 'settings:sidebarTogglePositionOptions.top-left',
      'top-right': 'settings:sidebarTogglePositionOptions.top-right',
      'top-center': 'settings:sidebarTogglePositionOptions.top-center',
    },
  },
  {
    key: 'sidebarNavLayout',
    category: 'appearance',
    type: 'select',
    default: 'vertical',
    options: ['vertical', 'compact'],
    labelKey: 'settings:appearance.sidebarNavLayout.label',
    descKey: 'settings:appearance.sidebarNavLayout.desc',
    optionLabels: {
      vertical: 'settings:sidebarNavLayoutOptions.vertical',
      compact: 'settings:sidebarNavLayoutOptions.compact',
    },
  },
  {
    key: 'showAssistantDelete',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantDelete.label',
    descKey: 'settings:appearance.showAssistantDelete.desc',
  },
  {
    key: 'showAssistantEdit',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantEdit.label',
    descKey: 'settings:appearance.showAssistantEdit.desc',
  },
  {
    key: 'showAssistantCopy',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantCopy.label',
    descKey: 'settings:appearance.showAssistantCopy.desc',
  },
  {
    key: 'showAssistantFork',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantFork.label',
    descKey: 'settings:appearance.showAssistantFork.desc',
  },
  {
    key: 'showAssistantRegenerate',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantRegenerate.label',
    descKey: 'settings:appearance.showAssistantRegenerate.desc',
  },
  {
    key: 'showAssistantSpeak',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantSpeak.label',
    descKey: 'settings:appearance.showAssistantSpeak.desc',
  },
  {
    key: 'showAssistantPrompt',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantPrompt.label',
    descKey: 'settings:appearance.showAssistantPrompt.desc',
  },
  {
    key: 'showAssistantDeleteAll',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantDeleteAll.label',
    descKey: 'settings:appearance.showAssistantDeleteAll.desc',
  },
  {
    key: 'showAssistantDeleteFromHere',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'assistantButtons',
    labelKey: 'settings:appearance.showAssistantDeleteFromHere.label',
    descKey: 'settings:appearance.showAssistantDeleteFromHere.desc',
  },
  {
    key: 'assistantButtonOrder',
    category: 'appearance',
    type: 'buttonOrder',
    default: [
      'delete',
      'deleteAll',
      'deleteFromHere',
      'edit',
      'copy',
      'fork',
      'regenerate',
      'speak',
      'prompt',
    ],
    group: 'assistantButtons',
    labelKey: 'settings:appearance.assistantButtonOrder.label',
    descKey: 'settings:appearance.assistantButtonOrder.desc',
    props: {
      buttons: [
        { key: 'delete', labelKey: 'settings:appearance.showAssistantDelete.label' },
        { key: 'deleteAll', labelKey: 'settings:appearance.showAssistantDeleteAll.label' },
        {
          key: 'deleteFromHere',
          labelKey: 'settings:appearance.showAssistantDeleteFromHere.label',
        },
        { key: 'edit', labelKey: 'settings:appearance.showAssistantEdit.label' },
        { key: 'copy', labelKey: 'settings:appearance.showAssistantCopy.label' },
        { key: 'fork', labelKey: 'settings:appearance.showAssistantFork.label' },
        { key: 'regenerate', labelKey: 'settings:appearance.showAssistantRegenerate.label' },
        { key: 'speak', labelKey: 'settings:appearance.showAssistantSpeak.label' },
        { key: 'prompt', labelKey: 'settings:appearance.showAssistantPrompt.label' },
      ],
    },
  },
  {
    key: 'showUserDelete',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserDelete.label',
    descKey: 'settings:appearance.showUserDelete.desc',
  },
  {
    key: 'showUserEdit',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserEdit.label',
    descKey: 'settings:appearance.showUserEdit.desc',
  },
  {
    key: 'showUserCopy',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserCopy.label',
    descKey: 'settings:appearance.showUserCopy.desc',
  },
  {
    key: 'showUserFork',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserFork.label',
    descKey: 'settings:appearance.showUserFork.desc',
  },
  {
    key: 'showUserDeleteAll',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserDeleteAll.label',
    descKey: 'settings:appearance.showUserDeleteAll.desc',
  },
  {
    key: 'showUserDeleteFromHere',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'userButtons',
    labelKey: 'settings:appearance.showUserDeleteFromHere.label',
    descKey: 'settings:appearance.showUserDeleteFromHere.desc',
  },
  {
    key: 'userButtonOrder',
    category: 'appearance',
    type: 'buttonOrder',
    default: ['delete', 'deleteAll', 'deleteFromHere', 'edit', 'copy', 'fork'],
    group: 'userButtons',
    labelKey: 'settings:appearance.userButtonOrder.label',
    descKey: 'settings:appearance.userButtonOrder.desc',
    props: {
      buttons: [
        { key: 'delete', labelKey: 'settings:appearance.showUserDelete.label' },
        { key: 'deleteAll', labelKey: 'settings:appearance.showUserDeleteAll.label' },
        { key: 'deleteFromHere', labelKey: 'settings:appearance.showUserDeleteFromHere.label' },
        { key: 'edit', labelKey: 'settings:appearance.showUserEdit.label' },
        { key: 'copy', labelKey: 'settings:appearance.showUserCopy.label' },
        { key: 'fork', labelKey: 'settings:appearance.showUserFork.label' },
      ],
    },
  },
  {
    key: 'showChatOOC',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatOOC.label',
    descKey: 'settings:appearance.showChatOOC.desc',
  },
  {
    key: 'showChatAttachFile',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatAttachFile.label',
    descKey: 'settings:appearance.showChatAttachFile.desc',
  },
  {
    key: 'showChatShortcuts',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatShortcuts.label',
    descKey: 'settings:appearance.showChatShortcuts.desc',
  },
  {
    key: 'showChatMemories',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatMemories.label',
    descKey: 'settings:appearance.showChatMemories.desc',
  },
  {
    key: 'showChatSTT',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatSTT.label',
    descKey: 'settings:appearance.showChatSTT.desc',
  },
  {
    key: 'showChatAutoTTS',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatAutoTTS.label',
    descKey: 'settings:appearance.showChatAutoTTS.desc',
  },
  {
    key: 'showChatEnterToSend',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatEnterToSend.label',
    descKey: 'settings:appearance.showChatEnterToSend.desc',
  },
  {
    key: 'showChatAutoReply',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatAutoReply.label',
    descKey: 'settings:appearance.showChatAutoReply.desc',
  },
  {
    key: 'showChatAutoSend',
    category: 'appearance',
    type: 'toggle',
    default: true,
    group: 'chatButtons',
    labelKey: 'settings:appearance.showChatAutoSend.label',
    descKey: 'settings:appearance.showChatAutoSend.desc',
  },
  {
    key: 'chatButtonOrder',
    category: 'appearance',
    type: 'buttonOrder',
    default: [
      'ooc',
      'attachFile',
      'shortcuts',
      'memories',
      'stt',
      'autoTTS',
      'enterToSend',
      'autoReply',
      'autoSend',
    ],
    group: 'chatButtons',
    labelKey: 'settings:appearance.chatButtonOrder.label',
    descKey: 'settings:appearance.chatButtonOrder.desc',
    props: {
      buttons: [
        { key: 'ooc', labelKey: 'settings:appearance.showChatOOC.label' },
        { key: 'attachFile', labelKey: 'settings:appearance.showChatAttachFile.label' },
        { key: 'shortcuts', labelKey: 'settings:appearance.showChatShortcuts.label' },
        { key: 'memories', labelKey: 'settings:appearance.showChatMemories.label' },
        { key: 'stt', labelKey: 'settings:appearance.showChatSTT.label' },
        { key: 'autoTTS', labelKey: 'settings:appearance.showChatAutoTTS.label' },
        { key: 'enterToSend', labelKey: 'settings:appearance.showChatEnterToSend.label' },
        { key: 'autoReply', labelKey: 'settings:appearance.showChatAutoReply.label' },
        { key: 'autoSend', labelKey: 'settings:appearance.showChatAutoSend.label' },
      ],
    },
  },
  {
    key: 'characterCardMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.characterCardMarquee.label',
    descKey: 'settings:appearance.characterCardMarquee.desc',
  },
  {
    key: 'threadCardMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.threadCardMarquee.label',
    descKey: 'settings:appearance.threadCardMarquee.desc',
  },
  {
    key: 'chatTitleMarquee',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.chatTitleMarquee.label',
    descKey: 'settings:appearance.chatTitleMarquee.desc',
  },
  {
    key: 'unreadBadges',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.unreadBadges.label',
    descKey: 'settings:appearance.unreadBadges.desc',
  },
  {
    key: 'highlightDeleteButtons',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.highlightDeleteButtons.label',
    descKey: 'settings:appearance.highlightDeleteButtons.desc',
  },
  {
    key: 'regenerationConfirmation',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.regenerationConfirmation.label',
    descKey: 'settings:appearance.regenerationConfirmation.desc',
  },
  {
    key: 'cancellationConfirmation',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.cancellationConfirmation.label',
    descKey: 'settings:appearance.cancellationConfirmation.desc',
  },
  {
    key: 'unreadSound',
    category: 'appearance',
    type: 'toggle',
    default: false,
    labelKey: 'settings:appearance.unreadSound.label',
    descKey: 'settings:appearance.unreadSound.desc',
  },
  {
    key: 'chatFontFamily',
    category: 'appearance',
    type: 'select',
    default: 'system',
    options: ['system', 'inter', 'atkinson', 'roboto', 'georgia', 'courier', 'trebuchet'],
    labelKey: 'settings:appearance.chatFontFamily.label',
    descKey: 'settings:appearance.chatFontFamily.desc',
    optionLabels: {
      system: 'settings:appearance.chatFontFamilyOptions.system',
      inter: 'settings:appearance.chatFontFamilyOptions.inter',
      atkinson: 'settings:appearance.chatFontFamilyOptions.atkinson',
      roboto: 'settings:appearance.chatFontFamilyOptions.roboto',
      georgia: 'settings:appearance.chatFontFamilyOptions.georgia',
      courier: 'settings:appearance.chatFontFamilyOptions.courier',
      trebuchet: 'settings:appearance.chatFontFamilyOptions.trebuchet',
    },
  },
  {
    key: 'chatFontSize',
    category: 'appearance',
    type: 'select',
    default: 'sm',
    options: ['xs', 'sm', 'base', 'lg', 'xl'],
    labelKey: 'settings:appearance.chatFontSize.label',
    descKey: 'settings:appearance.chatFontSize.desc',
    optionLabels: {
      xs: 'settings:appearance.chatFontSizeOptions.xs',
      sm: 'settings:appearance.chatFontSizeOptions.sm',
      base: 'settings:appearance.chatFontSizeOptions.base',
      lg: 'settings:appearance.chatFontSizeOptions.lg',
      xl: 'settings:appearance.chatFontSizeOptions.xl',
    },
  },
  {
    key: 'autoTitleMarker',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.autoTitleMarker.label',
    descKey: 'settings:appearance.autoTitleMarker.desc',
  },
  {
    key: 'summarizationMarker',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.summarizationMarker.label',
    descKey: 'settings:appearance.summarizationMarker.desc',
  },
  {
    key: 'trimAutoTitle',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.trimAutoTitle.label',
    descKey: 'settings:appearance.trimAutoTitle.desc',
  },
  {
    key: 'renderMarkdown',
    category: 'appearance',
    type: 'toggle',
    default: true,
    labelKey: 'settings:appearance.renderMarkdown.label',
    descKey: 'settings:appearance.renderMarkdown.desc',
  },
  {
    key: 'defaultAutoTitle',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.autoTitle.label',
    descKey: 'settings:defaults.autoTitle.desc',
  },
  {
    key: 'defaultAutoTitleThreshold',
    category: 'defaults',
    type: 'slider',
    default: 3,
    props: { min: 1, max: 10, step: 1 },
    labelKey: 'settings:defaults.autoTitleThreshold.label',
    descKey: 'settings:defaults.autoTitleThreshold.desc',
  },
  {
    key: 'defaultMemory',
    category: 'defaults',
    type: 'select',
    default: 'messages',
    options: ['never', 'messages', 'contextWindow'],
    labelKey: 'settings:defaults.memory.label',
    descKey: 'settings:defaults.memory.desc',
    optionLabels: {
      never: 'settings:defaults.memoryOptions.never',
      messages: 'settings:defaults.memoryOptions.messages',
      contextWindow: 'settings:defaults.memoryOptions.contextWindow',
    },
  },
  {
    key: 'defaultMessagesThreshold',
    category: 'defaults',
    type: 'slider',
    default: 7,
    props: { min: 3, max: 50, step: 1 },
    labelKey: 'settings:defaults.messagesThreshold.label',
    descKey: 'settings:defaults.messagesThreshold.desc',
    dependsOn: { key: 'defaultMemory', value: 'messages' },
  },
  {
    key: 'defaultContextWindowThreshold',
    category: 'defaults',
    type: 'slider',
    default: 1024,
    props: { min: 256, max: 8192, step: 128 },
    labelKey: 'settings:defaults.contextWindowThreshold.label',
    descKey: 'settings:defaults.contextWindowThreshold.desc',
    dependsOn: { key: 'defaultMemory', value: 'contextWindow' },
  },
  {
    key: 'defaultMessagesToKeep',
    category: 'defaults',
    type: 'slider',
    default: 5,
    props: { min: 0, max: 25, step: 1 },
    labelKey: 'settings:defaults.messagesToKeep.label',
    descKey: 'settings:defaults.messagesToKeep.desc',
    dependsOn: { key: 'defaultMemory', value: 'never', not: true },
  },
  {
    key: 'defaultMemorySlots',
    category: 'defaults',
    type: 'slider',
    default: 3,
    props: { min: 1, max: 5, step: 1 },
    labelKey: 'settings:defaults.memorySlots.label',
    descKey: 'settings:defaults.memorySlots.desc',
    dependsOn: { key: 'defaultMemory', value: 'never', not: true },
  },
  {
    key: 'defaultFirstMessage',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.firstMessage.label',
    descKey: 'settings:defaults.firstMessage.desc',
  },
  {
    key: 'defaultUserPersonaPrefix',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.userPersonaPrefix.label',
    descKey: 'settings:defaults.userPersonaPrefix.desc',
  },
  {
    key: 'defaultIncludeOOC',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.includeOOC.label',
    descKey: 'settings:defaults.includeOOC.desc',
  },
  {
    key: 'defaultMessageThreshold',
    category: 'defaults',
    type: 'text',
    default: 0,
    props: { type: 'number', min: 0 },
    labelKey: 'settings:defaults.unloadMessagesThreshold.label',
    descKey: 'settings:defaults.unloadMessagesThreshold.desc',
  },
  {
    key: 'defaultPostProcessing',
    category: 'defaults',
    type: 'toggle',
    default: true,
    labelKey: 'settings:defaults.postProcessing.label',
    descKey: 'settings:defaults.postProcessing.desc',
  },
  {
    key: 'defaultSystemAvatar',
    category: 'defaults',
    type: 'avatar',
    default: '',
    labelKey: 'settings:defaults.systemAvatar.label',
    descKey: 'settings:defaults.systemAvatar.desc',
  },
  {
    key: 'defaultSystemAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.systemAvatarScale.label',
    descKey: 'settings:defaults.systemAvatarScale.desc',
  },
  {
    key: 'defaultCharacterAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.characterAvatarScale.label',
    descKey: 'settings:defaults.characterAvatarScale.desc',
  },
  {
    key: 'defaultUserPersonaAvatarScale',
    category: 'defaults',
    type: 'select',
    default: '1x',
    options: ['1x', '2x', '3x', '4x'],
    labelKey: 'settings:defaults.userPersonaAvatarScale.label',
    descKey: 'settings:defaults.userPersonaAvatarScale.desc',
  },
  {
    key: 'requestKind.chat.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.chatProfile.label',
    descKey: 'settings:api.chatProfile.desc',
  },
  {
    key: 'requestKind.autoTitle.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.autoTitleProfile.label',
    descKey: 'settings:api.autoTitleProfile.desc',
  },
  {
    key: 'requestKind.summarization.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.summarizationProfile.label',
    descKey: 'settings:api.summarizationProfile.desc',
  },
  {
    key: 'requestKind.ooc.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.oocProfile.label',
    descKey: 'settings:api.oocProfile.desc',
  },
  {
    key: 'requestKind.director.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.directorProfile.label',
    descKey: 'settings:api.directorProfile.desc',
  },
  {
    key: 'requestKind.interface.profileId',
    category: 'api',
    type: 'text',
    default: null,
    labelKey: 'settings:api.interfaceProfile.label',
    descKey: 'settings:api.interfaceProfile.desc',
  },
  {
    key: 'api.requestCooldown',
    category: 'api',
    type: 'slider',
    default: 2,
    props: { min: 2, max: 10, step: 0.5 },
    labelKey: 'settings:api.requestCooldown.label',
    descKey: 'settings:api.requestCooldown.desc',
  },
  {
    key: 'api.requestTimeout',
    category: 'api',
    type: 'slider',
    default: 150,
    props: { min: 30, max: 300, step: 30 },
    labelKey: 'settings:api.requestTimeout.label',
    descKey: 'settings:api.requestTimeout.desc',
  },
  {
    key: 'prompting.autoTitleSystem',
    category: 'prompting',
    type: 'textarea',
    default: 'You are a title generator for conversational AI.\n\n{{transcript}}',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.autoTitleSystem.label',
    descKey: 'settings:prompting.autoTitleSystem.desc',
  },
  {
    key: 'prompting.autoTitleUser',
    category: 'prompting',
    type: 'textarea',
    default: 'Create a title for the provided message exchange.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.autoTitleUser.label',
    descKey: 'settings:prompting.autoTitleUser.desc',
  },
  {
    key: 'localInference.autoTitle',
    category: 'prompting',
    group: 'localInference',
    type: 'toggle',
    default: false,
    labelKey: 'settings:localInference.autoTitle.label',
    descKey: 'settings:localInference.autoTitle.desc',
  },
  {
    key: 'localInference.titleModel',
    category: 'prompting',
    group: 'localInference',
    type: 'select',
    default: 'title-generation',
    options: ['title-generation', 'title-generation-distilbart'],
    optionLabels: {
      'title-generation': 'settings:localInference.models.flanT5',
      'title-generation-distilbart': 'settings:localInference.models.distilbart',
    },
    dependsOn: { key: 'localInference.autoTitle', value: true },
    labelKey: 'settings:localInference.titleModel.label',
    descKey: 'settings:localInference.titleModel.desc',
  },
  {
    key: 'localInference.freeMemory',
    category: 'prompting',
    group: 'localInference',
    type: 'toggle',
    default: false,
    dependsOn: { key: 'localInference.autoTitle', value: true },
    labelKey: 'settings:localInference.freeMemory.label',
    descKey: 'settings:localInference.freeMemory.desc',
  },
  {
    key: 'localInference.repetitionPenalty',
    category: 'prompting',
    group: 'localInferenceAdvanced',
    type: 'slider',
    default: 1.3,
    props: { min: 1, max: 2, step: 0.1 },
    dependsOn: { key: 'localInference.autoTitle', value: true },
    labelKey: 'settings:localInference.repetitionPenalty.label',
    descKey: 'settings:localInference.repetitionPenalty.desc',
  },
  {
    key: 'localInference.noRepeatNgramSize',
    category: 'prompting',
    group: 'localInferenceAdvanced',
    type: 'slider',
    default: 3,
    props: { min: 0, max: 5, step: 1 },
    dependsOn: { key: 'localInference.autoTitle', value: true },
    labelKey: 'settings:localInference.noRepeatNgramSize.label',
    descKey: 'settings:localInference.noRepeatNgramSize.desc',
  },
  {
    key: 'localInference.maxNewTokens',
    category: 'prompting',
    group: 'localInferenceAdvanced',
    type: 'slider',
    default: 16,
    props: { min: 8, max: 64, step: 1 },
    dependsOn: { key: 'localInference.autoTitle', value: true },
    labelKey: 'settings:localInference.maxNewTokens.label',
    descKey: 'settings:localInference.maxNewTokens.desc',
  },
  {
    key: 'prompting.summarizationSystem',
    category: 'prompting',
    type: 'textarea',
    default:
      'You are an expert memory compressor for a roleplay conversation.\n\nYour task is to create a concise, factual update to the ongoing memory based on the chat history provided.\n\nRules:\n- Start from the previous memory (if any) and integrate only new key information.\n- Extract and condense important facts: character actions, decisions, relationship changes, locations, important objects, emotional states, and plot progression.\n- Use a neutral, matter-of-fact, third-person style.\n- Be concise: Maximum 2 short paragraphs, under 192 tokens total.\n- Never include quoted dialogue, inner thoughts, speculation, or invented details.\n- Do not add closure or continue the scene.\n- Eliminate any duplicate information already in the previous memory.\n- Output ONLY the updated memory text. No explanations or labels.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.summarizationSystem.label',
    descKey: 'settings:prompting.summarizationSystem.desc',
  },
  {
    key: 'prompting.summarizationUser',
    category: 'prompting',
    type: 'textarea',
    default: '{{transcript}}',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.summarizationUser.label',
    descKey: 'settings:prompting.summarizationUser.desc',
  },
  {
    key: 'prompting.directorSystem',
    category: 'prompting',
    type: 'textarea',
    default:
      "You are a rigorous director reviewing an AI roleplay response before it is shown to the user.\n\nYour task is to evaluate the response strictly against the character prompt and the defined writing style, and to rewrite it so that it fully complies.\n\nRules:\n- Enforce strict adherence to the character's personality, knowledge, motivations, and constraints from the character prompt.\n- Enforce the specified writing style: tone, POV, tense, prose density, formatting, and any style directives.\n- Remove or correct any content that breaks character, contradicts established facts, or violates the style definition.\n- Preserve the original meaning, intent, and narrative events unless they conflict with the above.\n- Output ONLY the corrected response text. No explanations, labels, or commentary.",
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.directorSystem.label',
    descKey: 'settings:prompting.directorSystem.desc',
  },
  {
    key: 'prompting.oocDelimiters',
    category: 'prompting',
    type: 'oocDelimiters',
    default: { enabled: true, left: '((OOC: ', right: '))' },
    labelKey: 'settings:prompting.oocDelimiters.label',
    descKey: 'settings:prompting.oocDelimiters.desc',
  },
  {
    key: 'prompting.oocSystem',
    category: 'prompting',
    type: 'textarea',
    default:
      'This is an OOC (out-of-character) request. Respond only in OOC mode. Be concise, direct, pragmatic, and exact. Do not roleplay, narrate, or continue the story.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.oocSystem.label',
    descKey: 'settings:prompting.oocSystem.desc',
  },
  {
    key: 'prompting.oocMessageRole',
    category: 'prompting',
    type: 'select',
    default: 'assistant',
    options: ['system', 'assistant'],
    labelKey: 'settings:prompting.oocMessageRole.label',
    descKey: 'settings:prompting.oocMessageRole.desc',
    optionLabels: {
      system: 'settings:prompting.oocMessageRoleOptions.system',
      assistant: 'settings:prompting.oocMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.oocUser',
    category: 'prompting',
    type: 'textarea',
    default: '{{content}}',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.oocUser.label',
    descKey: 'settings:prompting.oocUser.desc',
  },
  {
    key: 'prompting.personaInjectionTemplate',
    category: 'prompting',
    type: 'textarea',
    default:
      '**User Persona:**\n\n- Name: {{name}}.\n- Description: {{description}}.\n- Remember: Do not control or speak for the user.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.personaInjectionTemplate.label',
    descKey: 'settings:prompting.personaInjectionTemplate.desc',
  },
  {
    key: 'prompting.systemRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '**System:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.systemRolePrefix.label',
    descKey: 'settings:prompting.systemRolePrefix.desc',
  },
  {
    key: 'prompting.assistantRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '**Assistant:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.assistantRolePrefix.label',
    descKey: 'settings:prompting.assistantRolePrefix.desc',
  },
  {
    key: 'prompting.userRolePrefix',
    category: 'prompting',
    type: 'text',
    default: '**User:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.userRolePrefix.label',
    descKey: 'settings:prompting.userRolePrefix.desc',
  },
  {
    key: 'prompting.userRolePrefixWithPersona',
    category: 'prompting',
    type: 'text',
    default: '**User as {{name}}:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.userRolePrefixWithPersona.label',
    descKey: 'settings:prompting.userRolePrefixWithPersona.desc',
  },
  {
    key: 'prompting.systemRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '**System in OOC:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.systemRolePrefixOoc.label',
    descKey: 'settings:prompting.systemRolePrefixOoc.desc',
  },
  {
    key: 'prompting.assistantRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '**Assistant in OOC:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.assistantRolePrefixOoc.label',
    descKey: 'settings:prompting.assistantRolePrefixOoc.desc',
  },
  {
    key: 'prompting.userRolePrefixOoc',
    category: 'prompting',
    type: 'text',
    default: '**User in OOC:**',
    group: 'rolePrefixes',
    labelKey: 'settings:prompting.userRolePrefixOoc.label',
    descKey: 'settings:prompting.userRolePrefixOoc.desc',
  },
  {
    key: 'prompting.writingInjectionTiming',
    category: 'defaults',
    type: 'select',
    default: 'always',
    options: ['always', 'never'],
    labelKey: 'settings:defaults.writingInjectionTiming.label',
    descKey: 'settings:defaults.writingInjectionTiming.desc',
    optionLabels: {
      always: 'settings:defaults.writingInjectionTimingOptions.always',
      never: 'settings:defaults.writingInjectionTimingOptions.never',
    },
  },
  {
    key: 'prompting.writingPlacement',
    category: 'defaults',
    type: 'select',
    default: 'endOfSystemPrompt',
    options: ['endOfSystemPrompt', 'endOfMessages'],
    dependsOn: { key: 'prompting.writingInjectionTiming', value: 'always' },
    labelKey: 'settings:defaults.writingPlacement.label',
    descKey: 'settings:defaults.writingPlacement.desc',
    optionLabels: {
      endOfSystemPrompt: 'settings:defaults.writingPlacementOptions.endOfSystemPrompt',
      endOfMessages: 'settings:defaults.writingPlacementOptions.endOfMessages',
    },
  },
  {
    key: 'prompting.writingMessageRole',
    category: 'defaults',
    type: 'select',
    default: 'system',
    options: ['system', 'assistant'],
    dependsOn: [
      { key: 'prompting.writingPlacement', value: 'endOfMessages' },
      { key: 'prompting.writingInjectionTiming', value: 'always' },
    ],
    labelKey: 'settings:defaults.writingMessageRole.label',
    descKey: 'settings:defaults.writingMessageRole.desc',
    optionLabels: {
      system: 'settings:defaults.writingMessageRoleOptions.system',
      assistant: 'settings:defaults.writingMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.personaInjectionTiming',
    category: 'defaults',
    type: 'select',
    default: 'always',
    options: ['always', 'never'],
    labelKey: 'settings:defaults.personaInjectionTiming.label',
    descKey: 'settings:defaults.personaInjectionTiming.desc',
    optionLabels: {
      always: 'settings:defaults.personaInjectionTimingOptions.always',
      never: 'settings:defaults.personaInjectionTimingOptions.never',
    },
  },
  {
    key: 'personaInjectionPlacement',
    category: 'defaults',
    type: 'select',
    default: 'endOfSystemPrompt',
    options: ['endOfSystemPrompt', 'endOfMessages'],
    dependsOn: { key: 'prompting.personaInjectionTiming', value: 'always' },
    labelKey: 'settings:defaults.personaInjectionPlacement.label',
    descKey: 'settings:defaults.personaInjectionPlacement.desc',
    optionLabels: {
      endOfSystemPrompt: 'settings:defaults.personaInjectionPlacementOptions.endOfSystemPrompt',
      endOfMessages: 'settings:defaults.personaInjectionPlacementOptions.endOfMessages',
    },
  },
  {
    key: 'personaInjectionMessageRole',
    category: 'defaults',
    type: 'select',
    default: 'system',
    options: ['system', 'assistant'],
    dependsOn: [
      { key: 'personaInjectionPlacement', value: 'endOfMessages' },
      { key: 'prompting.personaInjectionTiming', value: 'always' },
    ],
    labelKey: 'settings:defaults.personaInjectionMessageRole.label',
    descKey: 'settings:defaults.personaInjectionMessageRole.desc',
    optionLabels: {
      system: 'settings:defaults.personaInjectionMessageRoleOptions.system',
      assistant: 'settings:defaults.personaInjectionMessageRoleOptions.assistant',
    },
  },
  {
    key: 'prompting.firstMessageRole',
    category: 'prompting',
    type: 'select',
    default: 'user',
    options: ['system', 'assistant', 'user'],
    labelKey: 'settings:prompting.firstMessageRole.label',
    descKey: 'settings:prompting.firstMessageRole.desc',
    optionLabels: {
      system: 'settings:prompting.firstMessageRoleOptions.system',
      assistant: 'settings:prompting.firstMessageRoleOptions.assistant',
      user: 'settings:prompting.firstMessageRoleOptions.user',
    },
  },
  {
    key: 'prompting.firstMessagePrompt',
    category: 'prompting',
    type: 'textarea',
    default:
      'Begin the interaction based on the provided system instructions and character/scenario definition. Provide the first response now. Follow all guidelines precisely.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.firstMessagePrompt.label',
    descKey: 'settings:prompting.firstMessagePrompt.desc',
  },
  {
    key: 'prompting.continueRole',
    category: 'prompting',
    type: 'select',
    default: 'user',
    options: ['system', 'assistant', 'user'],
    labelKey: 'settings:prompting.continueRole.label',
    descKey: 'settings:prompting.continueRole.desc',
    optionLabels: {
      system: 'settings:prompting.continueRoleOptions.system',
      assistant: 'settings:prompting.continueRoleOptions.assistant',
      user: 'settings:prompting.continueRoleOptions.user',
    },
  },
  {
    key: 'prompting.continuePrompt',
    category: 'prompting',
    type: 'textarea',
    default:
      'Continue the current output based on the system prompt. Generate the subsequent content without repetition.',
    props: { rows: 6, collapsible: true, summary: 'tokens' },
    labelKey: 'settings:prompting.continuePrompt.label',
    descKey: 'settings:prompting.continuePrompt.desc',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.characterPrompt',
    category: 'prompting',
    type: 'text',
    default: '**Main Prompt:**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.characterPrompt.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.writingInstruction',
    category: 'prompting',
    type: 'text',
    default: '**Writing Instructions:**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.writingInstruction.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.messages',
    category: 'prompting',
    type: 'text',
    default: '**Recent Chat History (in order):**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.messages.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.memories',
    category: 'prompting',
    type: 'text',
    default: '**Previous Memory:**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.memories.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.memoryEntry',
    category: 'prompting',
    type: 'text',
    default: '**Memory Level {{level}} Entry {{slot}}:**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.memoryEntry.label',
  },
  {
    key: 'prompting.apiRequestSectionHeaders.loreContext',
    category: 'prompting',
    type: 'text',
    default: '**Lore:**',
    group: 'apiRequestSectionHeaders',
    labelKey: 'settings:prompting.apiRequestSectionHeaders.loreContext.label',
  },
  {
    key: 'prompting.prefixAssistantRole',
    category: 'prompting',
    type: 'toggleInput',
    default: { enabled: false, value: '{{char}}: ' },
    labelKey: 'settings:prompting.prefixAssistantRole.label',
    descKey: 'settings:prompting.prefixAssistantRole.desc',
  },
  {
    key: 'prompting.prefixUserRole',
    category: 'prompting',
    type: 'toggleInput',
    default: { enabled: false, value: '{{name}}: ' },
    labelKey: 'settings:prompting.prefixUserRole.label',
    descKey: 'settings:prompting.prefixUserRole.desc',
  },
  {
    key: 'prompting.trimMessages',
    category: 'prompting',
    type: 'toggle',
    default: true,
    labelKey: 'settings:prompting.trimMessages.label',
    descKey: 'settings:prompting.trimMessages.desc',
  },
]

const SETTING_EFFECTS = {
  theme: (value) => {
    applyThemeClass(value)
    migrateColorsOnThemeChange(value)
  },
  language: (value) => i18n.changeLanguage(value),
  highlightDeleteButtons: (value) => {
    document.documentElement.classList.toggle('show-delete-highlight', !!value)
  },
}

export async function getSetting(key) {
  const rows = await db.settings.where('key').equals(key).toArray()
  const def = SETTINGS.find((s) => s.key === key)?.default
  if (rows.length > 1) {
    const keep = rows[rows.length - 1]
    await db.settings.bulkDelete(rows.filter((r) => r.id !== keep.id).map((r) => r.id))
    return keep.value ?? def ?? null
  }
  return rows[0]?.value ?? def ?? null
}

export async function setSetting(key, value) {
  const existing = await db.settings.where('key').equals(key).first()
  if (existing) {
    await db.settings.update(existing.id, { value })
  } else {
    await db.settings.add({ key, value })
  }
  SETTING_EFFECTS[key]?.(value)
  window.dispatchEvent(new CustomEvent('settings-changed', { detail: { key, value } }))
}
